export default function Home() {
  return (
    <div style={{ padding: '2rem', background: '#111', color: '#fff' }}>
      <h1>✅ AiKre8tive Stargate is Live!</h1>
      <p>Generated by the Verdict Pipeline and WhisperSync™.</p>
    </div>
  );
}
